---
title: "R Notebook"
output: html_notebook
---


```{r}
library(sp)
library(rgdal)
library(tidyverse)
library(sf)
library(tidyverse)
BostonBikes::extract_zip()
my_trip_data <- BostonBikes::enrich_geospatial()
head(my_trip_data)
write.csv(my_trip_data, "data/november_enriched.csv")
```

```{r}
neighbourhood_clean <- my_trip_data%>%
  mutate(neighbourhood = gsub('"', '', neighbourhood))
write.csv(my_trip_data, "data/november_enriched.csv")
```

```{r}
head(my_trip_data)

```

```{r}
library(tidyverse)
neighbourhood_array = sqldf::read.csv.sql("data/november_enriched.csv", "SELECT DISTINCT start_neighbourhood as neighbourhood FROM file")
head(neighbourhood_array)
```


```{r}
df <- sqldf::read.csv.sql("data/november_enriched.csv","SELECT start_neighbourhood,
  COUNT(*) as journeys
  FROM file
  WHERE start_neighbourhood is not null
```


```{r}
GROUP BY 1")%>%
  mutate(start_neighbourhood = gsub('"', '', start_neighbourhood))
head(df)
```

```{r}
ggplot(df, aes(x=journeys, y=start_neighbourhood)) + geom_bar(stat='identity')
```
```{r}
#MVE for shiny
library(tidyverse)
library(ggplot2)
library(shiny)
neighbourhood_quoted <- sqldf::read.csv.sql("../data/november_enriched.csv", "SELECT DISTINCT start_neighbourhood as neighbourhood FROM file")
neighbourhood_array <- neighbourhood_quoted%>%
  mutate(neighbourhood = gsub('"', '', neighbourhood))
neighbourhood_array <- as.list(neighbourhood_array)


# Define UI for application that draws a histogram
ui <- fluidPage(
    # Application title
    titlePanel("Old Faithful Geyser Data"),

    # Sidebar with a slider input for number of bins
    sidebarLayout(
        sidebarPanel(
          selectInput("neighbourhood",
                      "Neighbourhood:",
                      neighbourhood_array,
                      selected = "Roxbury"
                      ),
          selectInput("direction",
                      "Direction:",
                      c("Outbound" = "start_neighbourhood",
                        "Inbound" = "end_neighbourhood"),
                      selected = "Inbound")
          ),


        # Show a plot of the generated distribution
        mainPanel(
           plotOutput("view"),
           textOutput("demo"))))

# Define server logic required to draw a histogram
server <- function(input, output) {
  november_enriched <- read.csv("../data/november_enriched.csv")

  dataframe <- reactive({sqldf::sqldf(
  glue::glue("SELECT start_neighbourhood,
  COUNT(*) as journeys
  FROM november_enriched
  WHERE end_neighbourhood = '{input$neighbourhood}'
  GROUP BY 1"))
  })

  output$view <- renderPlot({
    p <- ggplot(dataframe(), aes(x=journeys, y=start_neighbourhood)) + geom_bar(stat='identity')
    print(p)
  })
}


# Run the application
shinyApp(ui = ui, server = server)

```

```{r}
nycounties <- rgdal::readOGR("https://rstudio.github.io/leaflet/json/nycounties.geojson") 
pal <- colorNumeric("viridis", NULL)

leaflet(nycounties) %>%
  addTiles() %>%
  addPolygons(stroke = FALSE, smoothFactor = 0.3, fillOpacity = 1,
    fillColor = ~pal(log10(pop)),
    label = ~paste0(county, ": ", formatC(pop, big.mark = ","))) %>%
  addLegend(pal = pal, values = ~log10(pop), opacity = 1.0,
    labFormat = labelFormat(transform = function(x) round(10^x)))
```

```{r}
boston_districts <- rgdal::readOGR("data/Boston_Neighborhoods.geojson") 
journeys <- sqldf::read.csv.sql("data/november_enriched.csv", "SELECT start_neighbourhood, COUNT(*) as journeys from file group by 1")%>%
  mutate(start_neighbourhood = gsub('"', '', start_neighbourhood))

boston_districts@data <- boston_districts@data %>%
  dplyr::left_join(journeys, by = c("Name" = "start_neighbourhood"))

pal <- colorNumeric("viridis", NULL)


leaflet(boston_districts) %>%
  addTiles()%>%
  addPolygons(stroke = FALSE, smoothFactor = 0.3, fillOpacity = 0.6,
    fillColor = ~pal(boston_districts@data$journeys))%>%
  addLegend(pal = pal, values = boston_districts@data$journeys, opacity = 1.0)
```


```{r}
sqldf::read.csv.sql("data/november_enriched.csv", "SELECT * from file limit 10")%>%
  mutate(start_neighbourhood = gsub('"', '', start_neighbourhood))
```
```{r}


db < Sys.getenv("postgresql_db")
host_db <- 'localhost' #i.e. # i.e. 'ec2-54-83-201-96.compute-1.amazonaws.com'  

db_port <- Sys.getenv("postgresql_port")

db_user <- Sys.getenv("postgresql_user")

db_password <- Sys.getenv("postgresql_password")

con <- DBI::dbConnect(RPostgres::Postgres(), dbname = Sys.getenv("postgresql_db"), host='localhost', port=Sys.getenv("postgresql_port"), user=Sys.getenv("postgresql_user"), password=Sys.getenv("postgresql_password"))  

DBI::dbGetQuery(con, "SELECT * FROM stations") 
```

